# Generated by Django 4.2 on 2023-04-11 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(max_length=20)),
                ('password', models.CharField(max_length=64)),
                ('freelancer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('authTable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='freelancer.auth')),
                ('address', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='profile_pic')),
                ('aboutMe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
                ('authTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.auth')),
            ],
        ),
    ]
