# Generated by Django 4.2 on 2023-04-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
