# Generated by Django 4.2 on 2023-04-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_alter_auth_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='auth',
            name='verified',
            field=models.BooleanField(null=True),
        ),
    ]
