# Generated by Django 4.2 on 2023-04-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_auth_created_date_auth_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='token',
            field=models.CharField(max_length=65, null=True),
        ),
    ]
