# Generated by Django 4.2 on 2023-04-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0004_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='lastseen',
            field=models.DateTimeField(null=True),
        ),
    ]
