# Generated by Django 4.2 on 2023-04-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0005_auth_lastseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='devlopertag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
