# Generated by Django 4.2 on 2023-04-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0006_profile_devlopertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experiance',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
