# Generated by Django 4.2 on 2023-04-29 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0007_profile_experiance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=64)),
                ('projectDisc', models.TextField()),
                ('projectTime', models.CharField(max_length=64)),
                ('projectLang', models.CharField(max_length=64)),
                ('authTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.auth')),
            ],
        ),
        migrations.CreateModel(
            name='profileproj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projName', models.CharField(max_length=64)),
                ('projDisc', models.TextField()),
                ('projTime', models.CharField(max_length=64)),
                ('projLang', models.CharField(max_length=64)),
                ('authTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.auth')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgid', models.UUIDField()),
                ('msgsub', models.CharField(max_length=255)),
                ('msgbody', models.TextField()),
                ('msgtime', models.DateTimeField()),
                ('msgread', models.BooleanField()),
                ('authTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.auth')),
            ],
        ),
    ]
