# Generated by Django 4.2 on 2023-05-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0009_message_msgrecipent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='experiance',
            new_name='experience',
        ),
    ]
